### ISSUE TITLE
Difference between neo4j-contrib/gremlin-plugin and thinkaurelius/neo4j-gremlin-plugin?

### ISSUE THREAD

**Issue by einheitlix** [thinkaurelius/neo4j-gremlin-plugin#9]
Hi,

I'm confused as to the difference between the [neo4j-contrib/gremlin-plugin](https://github.com/neo4j-contrib/gremlin-plugin) and the [thinkaurelius/neo4j-gremlin-plugin](https://github.com/thinkaurelius/neo4j-gremlin-plugin). At first glance I thought that the former was for Neo4J 1.x, while the latter is for Neo4J 2.x, as the README here states

> The Neo4j Gremlin Plugin provides the ability to query/traverse a Neo4j graph using Gremlin via Neo4j Server 2.x. For Neo4j Server 1.x, please see the following project by Peter Neubauer: [neo4j-contrib/gremlin-plugin](https://github.com/neo4j-contrib/gremlin-plugin)

But I turns out that this is not the case. I tested the following combinations of Neo4J server and the respectively most recent versions of the two Gremlin plugins:

* Neo4J 2.1.8 with neo4j-contrib/gremlin-plugin@439024a10c20dbf79d30ea81ec2d24e3df637138: Works.
* Neo4J 2.2.3 with neo4j-contrib/gremlin-plugin@439024a10c20dbf79d30ea81ec2d24e3df637138: Does not work.
* Neo4J 2.1.8 with thinkaurelius/neo4j-gremlin-plugin@b40e333312e2ac72abdd7bd2ffe6236ffa2c02a3: Works. 
* Neo4J 2.2.3 with thinkaurelius/neo4j-gremlin-plugin@b40e333312e2ac72abdd7bd2ffe6236ffa2c02a3: Does not work.

In short, both plugins appear to work with Neo4J 2.1, while neither works with Neo4J 2.2. Note:
* When I say "works", I mean that I can successfully start the server and execute a simple Gremlin script using `curl` and the server responds correctly. I did not do any fancy/extensive testing beyond that.
* When I say "does not work", I mean that in both cases, I can successfully start the server, however when I try to send a simple Gremlin script using `curl`, in both cases a `java.lang.NoClassDefFoundError` is thrown as the `javax/transaction/SystemException` class cannot be found (except that the neo4j-contrib plugin sends the stack trace as a JSON response, while the thinkaurelius plugin prints the stack trace to the Neo4J console log.) Also see issue #8.

So, there are no newer versions of Neo4J that only work with the thinkaurelius plugin but not with the neo4j-contrib plugin, as I originally assumed. Apart from that, I only found some minor differences:
* The thinkaurelius plugin takes Gremlin scripts as GET requests; the neo4j-contrib plugin takes Gremlin scripts as POST requests.
* The thinkaurelius plugin expects scripts at `/tp/gremlin/execute`; the neo4j-contrib plugin expects scripts at `/db/data/ext/GremlinPlugin/graphdb/execute_script`.
* The thinkaurelius plugin needs the line

        org.neo4j.server.thirdparty_jaxrs_classes=com.thinkaurelius.neo4j.plugins=/tp

    in its `neo4j-server.properties` file, while the neo4j-contrib plugins needs no such thing.
* In the thinkaurelius plugin, the JSON result of a Gremlin script is sent back to the client wrapped like so: `{"results":<RESULT>,"success":true}`, while the neo4j-contrib plugin simply sends back `<RESULT>`.

But those are minor, technical details. Is there any fundamental difference between the two plugins? Any reason to prefer one over the other?

**Comment by dkuppitz** [comment]
When we initially wrote this plugin, the `neo4j-contrib` plugin didn't work at all with Neo4j 2.x. However, the code for both plugins should be pretty similar. I guess the main difference is the result serializer.

**Comment by einheitlix** [comment]
Oh, I see, thanks. :)
In that case, are there any plans to continue development of this plugin in the future (e.g., make it compatible with Neo4J 2.2) ?

**Comment by dkuppitz** [comment]
I was hoping that someone offers a PR for 2.2. I really have no idea where those `NoClassDefFoundError`s come from and I don't think that we're going to spend much more time on this plugin. Unfortunately it's already the 3rd time, that a minor release broke the plugin, so I guess it's better to give it all back into Neo4j's hands. We should (and probably will) set our focus on the [TP3 Neo4j integration](http://tinkerpop.incubator.apache.org/docs/3.1.0-SNAPSHOT/#neo4j-gremlin).

**Comment by einheitlix** [comment]
I understand. Thank you very much for the information, and good luck with the TP3 Neo4J integration! :-)
